//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IGT4.rc
//
#define IDCANCEL2                       3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IGT4_DIALOG                 102
#define IDD_SPR_AUTO_EXTRACT            103
#define IDR_MAINFRAME                   128
#define IDB_B_TOOL_ANI_SPR              129
#define IDI_TOOL_ANI_SPR                131
#define IDI_TOOL_AUTO_SPR               132
#define IDI_TOOL_MAP_TILE               133
#define IDC_C_NORMAL                    135
#define IDD_ANI_OBJ                     136
#define IDD_SPR_MERGE                   140
#define IDD_BMP_CONVERT                 141
#define IDD_RESRC                       142
#define IDD_LOOK                        143
#define IDD_FOLDER_BROWSE               144
#define IDD_ITEM                        145
#define IDD_COLOR                       147
#define IDD_COLOR_BLT_TEST              148
#define IDD_HOUSE_NUMBER                150
#define IDD_HOUSE_OPTION                151
#define IDC_B_SPR_INSERT_BLANK          200
#define IDC_LIST_REMARK                 201
#define IDC_B_SPR_FILE_NAME_COPY        202
#define IDC_B_SPR_FILE_NAME_PASTE       203
#define IDC_B_ACTIVATE_TOOL_ANI_SPR     1000
#define IDC_B_ACTIVATE_TOOL_MAP_TILE    1001
#define IDC_B_ACTIVATE_TOOL_AUTO_SPR    1002
#define IDC_B_WORK_PATH_SET             1003
#define IDC_E_WORK_PATH                 1004
#define IDC_SLIDER_SPR                  1005
#define IDC_B_ACTIVATE_TOOL_INTF        1005
#define IDC_E_ANI_FILE_NAME             1006
#define IDC_B_ACTIVATE_TOOL_SCRIPT      1006
#define IDC_E_SPR_CUR                   1007
#define IDC_B_ACTIVATE_TOOL_SPR_MERGE   1007
#define IDC_E_SPR_WHOLE                 1008
#define IDC_B_ACTIVATE_TOOL_CONVERT_BMP 1008
#define IDC_E_SPR_FILE_NAME             1009
#define IDC_B_ACTIVATE_TOOL_TMP         1009
#define IDC_B_ACTIVATE_TOOL_CONVERT_ANI 1009
#define IDC_CB_WORK                     1010
#define IDC_B_ACTIVATE_TOOL_LOOK_EDIT   1010
#define IDC_E_SPR_FILE_NAME2            1011
#define IDC_E_SPR_BMP_FILE_NAME         1011
#define IDC_B_ACTIVATE_TOOL_ITEM_EDIT   1011
#define IDC_B_SPR_SET_QT                1012
#define IDC_B_ACTIVATE_TOOL_TEST_COLOR_PROCESS 1012
#define IDC_E_SPR_QT                    1013
#define IDC_B_ACTIVATE_TOOL_CONVERT_SPR 1013
#define IDC_C_SPR_CK_R                  1014
#define IDC_B_ACTIVATE_TOOL_CONVERT_SPR2 1014
#define IDC_B_ACTIVATE_TOOL_RESRC       1014
#define IDC_C_SPR_CK_G                  1015
#define IDC_C_SPR_CK_B                  1016
#define IDC_B_CHR_REG                   1016
#define IDC_B_OBJ_REG                   1016
#define IDC_B_ANI_FILE_NAME_SET         1016
#define IDC_C_SPR_CENTER_R              1017
#define IDC_B_CHR_UNREG                 1017
#define IDC_B_OBJ_UNREG                 1017
#define IDC_B_ANI_FILE_NAME_DELETE      1017
#define IDC_C_SPR_CENTER_G              1018
#define IDC_SPREAD_MAP_CHR_REG          1018
#define IDC_B_SPR_FILE_NAME_SET         1018
#define IDC_C_SPR_CENTER_B              1019
#define IDC_B_SPR_FILE_NAME_DELETE      1019
#define IDC_E_CHR_FILE_NAME             1020
#define IDC_B_SPR_FILE_NAME_SET2        1020
#define IDC_CB_CHR_SPR                  1021
#define IDC_B_SPR_FILE_NAME_DELETE2     1021
#define IDC_B_CHR_SET_SPR               1022
#define IDC_B_SPR_FILE_NAME_SET3        1022
#define IDC_B_CHR_DELETE_SPR            1023
#define IDC_B_SPR_FILE_NAME_DELETE3     1023
#define IDC_LIST_SPR                    1024
#define IDC_B_SPR_FILE_NAME_SET4        1024
#define IDC_B_SPR_SET                   1025
#define IDC_B_SPR_FILE_NAME_DELETE4     1025
#define IDC_B_SPR_INSERT                1026
#define IDC_B_SPR_ADD                   1027
#define IDC_B_SPR_MERGE                 1028
#define IDC_B_SPR_LIST_SAVE             1029
#define IDC_B_SPR_LIST_LOAD             1030
#define IDC_B_SPR_LIST_NEW              1031
#define IDC_E_SPR_LIST_FILE_NAME        1032
#define IDC_B_SPR_LIST_SAVE_AS          1033
#define IDC_C_ANI_GENERATE_AUTO         1034
#define IDC_E_MAP_FILE_NAME             1034
#define IDC_B_SPR_DELETE                1035
#define IDC_E_MAP_FILE_NAME2            1035
#define IDC_B_OBJ_POST_QT_SET           1036
#define IDC_E_MAP_FILE_NAME3            1036
#define IDC_LIST_DATA                   1036
#define IDC_LIST_TILE_SET               1037
#define IDC_E_MAP_FILE_NAME4            1037
#define IDC_LIST_TILE_SUB_SET           1038
#define IDC_E_MAP_FILE_NAME5            1038
#define IDC_LIST_AVATA0                 1038
#define IDC_E_TILE_SUB_SET_NAME         1039
#define IDC_LIST_AVATA1                 1039
#define IDC_C_NEXT_AUTO                 1040
#define IDC_E_TILE_SET_NAME             1040
#define IDC_LIST_NPC                    1040
#define IDC_E_TILE_SUB_SET_NUMBER       1041
#define IDC_E_TILE_SET_NUMBER           1042
#define IDC_B_TILE_SET_IMPORT           1043
#define IDC_E_AVATA0_NUMBER             1043
#define IDC_B_TILE_SET_EXPORT           1044
#define IDC_B_SAVE_TILE_MAP_TO_GAME_FORMAT 1045
#define IDC_E_AVATA1_NUMBER             1045
#define IDC_LIST_FILES                  1046
#define IDC_E_AVATA0_NUMBER3            1046
#define IDC_E_NPC_NUMBER                1046
#define IDC_B_ADD_FILE                  1047
#define IDC_B_REMOVE_FILE               1048
#define IDC_B_BMP_TO_OBM                1049
#define IDC_B_OBM_TO_BMP                1050
#define IDC_CB_INTF_TYPE                1050
#define IDC_E_FLAG0                     1052
#define IDC_E_FLAG1                     1053
#define IDC_E_FLAG2                     1054
#define IDC_E_FLAG3                     1055
#define IDC_E_A                         1056
#define IDC_E_R                         1057
#define IDC_E_G                         1058
#define IDC_E_B                         1059
#define IDC_E_SPR                       1060
#define IDC_E_DATA                      1063
#define IDC_C_VIEW_BKG                  1064
#define IDC_B_MOVE_POS_UP               1065
#define IDC_B_MOVE_POS_DOWN             1066
#define IDC_BUTTON1                     1066
#define IDC_B_MAP_BROWSE                1066
#define IDC_B_RGN_INIT                  1066
#define IDC_DEL_TILESET                 1066
#define IDC_BUTTON2                     1067
#define IDC_B_MAP_DELETE                1067
#define IDC_GO_POS                      1067
#define IDC_B_LOAD_LIGHT_SOURCE_DATA    1067
#define IDC_B_ACTIVATE_TOOL_CONVERT_TILESET 1067
#define IDC_BUTTON3                     1068
#define IDC_CB_PART                     1068
#define IDC_B_AVATA0_BROWSE             1068
#define IDC_B_SAVE_LIGHT_SOURCE_DATA    1068
#define IDC_BUTTON4                     1069
#define IDC_B_AVATA0_DELETE             1069
#define IDC_B_NEW_LIGHT_SOURCE_DATA     1069
#define IDC_BUTTON5                     1070
#define IDC_LIST_ANI                    1070
#define IDC_B_AVATA1_BROWSE             1070
#define IDC_B_SAVE_TS_SPL               1070
#define IDC_B_BROWSE_SPR                1071
#define IDC_B_AVATA1_DELETE             1071
#define IDC_B_BROWSE_ANI                1072
#define IDC_B_AVATA_BROWSE3             1072
#define IDC_B_NPC_SHADOW_BROWSE         1072
#define IDC_B_NEW                       1073
#define IDC_B_LOAD                      1074
#define IDC_B_SAVE                      1075
#define IDC_B_SAVE_AS                   1076
#define IDC_E_FILE_NAME                 1077
#define IDC_B_AVATA_DELETE3             1077
#define IDC_B_NPC_SHADOW_DELETE         1077
#define IDC_B_AVATA_BROWSE4             1078
#define IDC_B_NPC_SPR_BROWSE            1078
#define IDC_B_AVATA_DELETE4             1079
#define IDC_B_NPC_SPR_DELETE            1079
#define IDC_B_AVATA_BROWSE5             1080
#define IDC_B_NPC_ANI_BROWSE            1080
#define IDC_B_AVATA_DELETE5             1081
#define IDC_B_NPC_ANI_DELETE            1081
#define IDC_C_ANIMATION                 1088
#define IDC_E_LOOK_PART_ASSEMBLE_QT     1089
#define IDC_E_ANI_QT                    1089
#define IDC_B_ASSEMBLE_QT_SET           1090
#define IDC_B_ANI_QT_SET                1090
#define IDC_E_ANI_PERIOD0               1091
#define IDC_E_PERIOD                    1091
#define IDC_E_ANI_PERIOD1               1092
#define IDC_E_PERIOD_RND                1092
#define IDC_LIST_WORK                   1093
#define IDC_E_LOOK_PART_ASSEMBLE_QT2    1094
#define IDC_E_LOOK_QT                   1094
#define IDC_B_ASSEMBLE_QT_SET2          1095
#define IDC_B_LOOK_QT_SET               1095
#define IDC_CB_LOOK                     1096
#define IDC_LIST_PART                   1097
#define IDC_LIST_PART_ANI               1097
#define IDC_E_PART_QT                   1098
#define IDC_B_PART_QT_SET               1099
#define IDC_R_SPL                       1101
#define IDC_B_COPY                      1101
#define IDC_R_SP8                       1102
#define IDC_B_PASTE                     1102
#define IDC_REMOVE_PIXEL_DELTA          1103
#define IDC_CB_RECENT_FOLDER            1103
#define IDC_BROWSE_WORK_FOLDER_AND_START_WORKING 1104
#define IDC_B_TUNNEL_TREE               1104
#define IDC_CANCEL_PROCESS              1105
#define IDC_CLOSEDLG                    1106
#define IDC_LB_ITEM                     1106
#define IDC_PROGRESS                    1107
#define IDC_E_STRENGTH                  1107
#define IDC_FILE_NAME                   1108
#define IDC_E_SPIRIT                    1108
#define IDC_STATIC_PREVIEW              1109
#define IDC_LB_ANI                      1109
#define IDC_C_REINFORCE                 1110
#define IDC_E_CHARM                     1110
#define IDC_E_IQ                        1111
#define IDC_E_EQ                        1112
#define IDC_E_LUCK                      1113
#define IDC_E_EXTRA0                    1114
#define IDC_E_REMARK                    1115
#define IDC_S_PREVIEW                   1116
#define IDC_B_QT_SET                    1117
#define IDC_E_EXTRA1                    1118
#define IDC_E_EXTRA2                    1119
#define IDC_E_EXTRA3                    1120
#define IDC_E_SPECIAL0                  1121
#define IDC_E_QT                        1122
#define IDC_E_NAME                      1123
#define IDC_E_WIDTH                     1124
#define IDC_SLD_R                       1124
#define IDC_E_SPECIAL1                  1125
#define IDC_E_SPECIAL2                  1126
#define IDC_STATIC_COLOR                1126
#define IDC_E_SPECIAL3                  1127
#define IDC_B_SPR_BROWSE                1127
#define IDC_E_DURABILITY                1128
#define IDC_LIST_MAP                    1128
#define IDC_E_STRENGTH_NEED             1129
#define IDC_E_MAP_NUMBER                1129
#define IDC_E_SPIRIT_NEED               1130
#define IDC_SLD_G                       1130
#define IDC_E_CHARM_NEED                1131
#define IDC_SLD_B                       1131
#define IDC_RADIO_NO_EDIT               1131
#define IDC_E_IQ_NEED                   1132
#define IDC_SLD_SPR                     1132
#define IDC_RADIO_MOVE_EDIT             1132
#define IDC_E_EQ_NEED                   1133
#define IDC_RADIO_HOUSE_EDIT            1133
#define IDC_E_LUCK_NEED                 1134
#define IDC_HOUSE_NUMBER                1134
#define IDC_E_EXTRA0_NEED               1135
#define IDC_RADIO_EVENT_EDIT            1135
#define IDC_E_EXTRA1_NEED               1136
#define IDC_RADIO_AREA_EDIT             1136
#define IDC_E_EXTRA2_NEED               1137
#define IDC_E_EXTRA3_NEED               1138
#define IDC_CHECK_HOUSEOPTION           1138
#define IDC_LIST_HOUSE                  1138
#define IDC_E_REMARK_NPC                1139
#define IDC_RADIO_NOMOVE                1140
#define IDC_E_HOUSE_NUMBER              1140
#define IDC_E_HEIGHT                    1141
#define IDC_RADIO_MOVABLE               1141
#define IDC_CHECK_HOUSE                 1142
#define IDC_RADIO_NOTMOVABLE            1143
#define IDC_RADIO_NOHOUSE               1144
#define IDC_RADIO_HOUSE                 1145
#define IDC_E_HOUSE_LIST_FILE_NAME      1146
#define IDC_SIZE_X                      1147
#define IDC_SIZE_Y                      1148
#define IDC_E_LIGHT_SOURCE_QT           1149
#define IDC_E_LIGHT_SOURCE_NUMBER       1150
#define IDC_B_LIGHT_SOURCE_COLOR_SET    1151
#define IDC_CELLSIZE                    1152
#define IDC_AREA_NUMBER                 1153
#define IDC_CHECK_SHOW_INNERHOUSE       1154
#define IDC_C_TILE_SET                  1155
#define IDC_CHECK_TILE_ANIMATION        1158
#define IDC_B_TILE_ANI_ADD              1159
#define IDC_B_TILE_ANI_DEL              1160
#define IDC_EDIT_ANI_SUB_SET_NAME       1161
#define IDC_EDIT_ANI_SUB_SET_NUMBER     1162
#define IDC_LIST_ANI_SUB_SETS           1163
#define IDC_B_TILE_ANIMATION            1164
#define IDC_C_OBJ_PRE_VIEW              1165
#define IDD_FOLDER_SELECT               1201
#define IDC_BROWSE_TREE                 1202
#define IDC_FOLDER_LIST                 1203
#define IDC_TUNNEL_TREE                 1204
#define IDD_SET_CENTER                  1300
#define IDC_CENTER_X                    1301
#define IDC_CENTER_Y                    1302
#define IDC_INIT_CENTER_OFFSET          1303
#define IDC_VIEW_PICTURE                1304
#define IDC_FRAME_PREV                  1400
#define IDC_B_ANI_FRM_PREV              1400
#define IDC_FRAME_NEXT                  1401
#define IDC_B_ANI_FRM_NEXT              1401
#define IDC_FRAME_VALUE                 1402
#define IDC_E_ANI_SPR                   1402
#define IDC_ANI_NUMBER                  1403
#define IDC_FRAME                       1404
#define IDC_E_ANI_CUR_FRM               1404
#define IDC_MAX_FRAME                   1405
#define IDC_E_ANI_MAX_FRM               1405
#define IDC_ANI_SPEED                   1406
#define IDC_E_ANI_SPEED                 1406
#define IDC_PLAY                        1407
#define IDC_B_ANI_PLAY                  1407
#define IDC_GET_FRAMES_FROM_STRING      1408
#define IDC_B_ANI_FRMS_GET_FROM_STRING  1408
#define IDC_VIEW_BKG                    1409
#define IDC_RADIO_DIR0                  1410
#define IDC_RADIO_DIR1                  1411
#define IDC_RADIO_DIR2                  1412
#define IDC_RADIO_DIR3                  1413
#define IDC_RADIO_DIR4                  1414
#define IDC_RADIO_DIR5                  1415
#define IDC_RADIO_DIR6                  1416
#define IDC_RADIO_DIR7                  1417
#define IDC_E_ANI_FRMS                  1419
#define IDC_B_ANI_SET_DIR_QT            1420
#define IDC_E_ANI_DIR_QT                1421
#define IDC_CB_DIR                      1422
#define IDC_ADD                         1427
#define IDC_B_ANI_ADD                   1427
#define IDC_DELETE                      1428
#define IDC_B_ANI_DELETE                1428
#define IDC_NEW                         1429
#define IDC_ANI_NEW                     1429
#define IDC_B_ANI_NEW                   1429
#define IDC_LOAD                        1430
#define IDC_ANI_LOAD                    1430
#define IDC_B_ANI_LOAD                  1430
#define IDC_SAVE                        1431
#define IDC_ANI_SAVE                    1431
#define IDC_B_ANI_SAVE                  1431
#define IDC_SAVE_AS                     1432
#define IDC_ANI_SAVE_AS                 1432
#define IDC_B_ANI_SAVE_AS               1432
#define IDC_INSERT                      1433
#define IDC_B_ANI_INSERT                1433
#define IDC_SPR_NEW                     1434
#define IDC_B_SPR_NEW                   1434
#define IDC_PASTE_ANI                   1435
#define IDC_B_ANI_PASTE                 1435
#define IDC_COPY_ANI                    1436
#define IDC_B_ANI_COPY                  1436
#define IDC_BROWSE_BKG_BMP              1437
#define IDC_B_BROWSE_BKG_BMP            1437
#define IDC_MAKE_FRMAES_SAME_TO_FRONT   1438
#define IDC_B_ANI_FRMS_SET_SAME_TO_FRONT 1438
#define IDC_GET_AUTO_SEQ_FRAMES         1439
#define IDC_B_ANI_FRMS_GET_AUTO_SEQ     1439
#define IDC_ANI_LIST                    1440
#define IDC_ANI_NAME                    1441
#define IDC_SPR_EXPORT_TO_BMP           1442
#define IDC_B_SPR_EXPORT_TO_BMP         1442
#define IDC_SPR_IMPORT_FROM_BMP         1443
#define IDC_B_SPR_IMPORT_FROM_BMP       1443
#define IDC_GET_AUTO_FRAMES_FROM_FRONT  1446
#define IDC_B_ANI_FRMS_GET_AUTO_FROM_FRONT 1446
#define IDC_SPR_LOAD                    1447
#define IDC_B_SPR_LOAD                  1447
#define IDC_SPR_SAVE_AS                 1448
#define IDC_B_SPR_SAVE_AS               1448
#define IDC_SPR_SAVE                    1449
#define IDC_B_SPR_SAVE                  1449
#define IDC_B_SPR_BROWSE_BMP            1450
#define IDC_B_CHR_LOAD                  1451
#define IDC_B_CHR_NEW                   1452
#define IDC_B_CHR_SAVE                  1453
#define IDC_B_CHR_SAVE_AS               1454
#define IDC_E_ANI_NUMBER                1455
#define IDC_ACT_ANI                     1455
#define IDD_TILE_MAP                    2001
#define IDC_BROWSE_BMP                  2002
#define IDC_B_BROWSE_BMP                2002
#define IDC_TREE_TILE_SET               2003
#define IDC_TILE_SET_ADD                2004
#define IDC_B_TILE_SET_ADD              2004
#define IDC_TILE_SET_DELETE             2005
#define IDC_B_TILE_SET_DELETE           2005
#define IDC_R_WORK_TILE_SET             2006
#define IDC_R_WORK_TILE_MAP             2007
#define IDC_TILE_SET_SUBSET_ADD         2008
#define IDC_B_TILE_SET_SUBSET_ADD       2008
#define IDC_TILE_SET_SUBSET_DELETE      2009
#define IDC_B_TILE_SET_SUBSET_DELETE    2009
#define IDC_EDIT_TILE_SUB_SET_WIDTH     2010
#define IDC_EDIT_TILE_SUB_SET_HEIGHT    2011
#define IDC_NEW_TILE_SET                2013
#define IDC_B_NEW_TILE_SET              2013
#define IDC_LOAD_TILE_SET               2014
#define IDC_B_LOAD_TILE_SET             2014
#define IDC_SAVE_AS_TILE_SET            2015
#define IDC_B_SAVE_AS_TILE_SET          2015
#define IDC_E_FILE_NAME_TILE_SET        2016
#define IDC_SAVE_TILE_SET               2017
#define IDC_B_SAVE_TILE_SET             2017
#define IDC_CHECK_VIEW_GRID             2018
#define IDC_PREVIEW_TILE_SUB_SET        2019
#define IDC_BMP_FILE_NAME_TILE_SET      2020
#define IDC_CHECK_TILE_SET_T_R          2021
#define IDC_CHECK_TILE_SET_T_G          2022
#define IDC_CHECK_TILE_SET_T_B          2023
#define IDC_NEW_TILE_MAP                2024
#define IDC_B_NEW_TILE_MAP              2024
#define IDC_LOAD_TILE_MAP               2025
#define IDC_B_LOAD_TILE_MAP             2025
#define IDC_SAVE_AS_TILE_MAP            2026
#define IDC_B_SAVE_AS_TILE_MAP          2026
#define IDC_E_FILE_NAME_TILE_MAP        2027
#define IDCI_SAVE_TILE_MAP              2028
#define IDC_B_SAVE_TILE_MAP             2028
#define IDC_LB_LAYER                    2029
#define IDC_CHECK_LAYER_HIDE            2030
#define IDC_SB_PREVIEW_H                2031
#define IDC_SB_PREVIEW_V                2032
#define IDC_EDIT_TILE_MAP_WIDTH         2033
#define IDC_EDIT_TILE_MAP_HEIGHT        2034
#define IDC_TILE_MAP_SET_SIZE           2035
#define IDC_B_TILE_MAP_SET_SIZE         2035
#define IDC_TILE_MAP_INIT_RANDOM        2036
#define IDC_B_TILE_MAP_INIT_RANDOM      2036
#define IDC_EDIT_TILE_MAP_INIT_RANDOM   2037
#define IDC_TILE_MAP_INIT               2038
#define IDC_B_TILE_MAP_INIT             2038
#define IDC_CHECK_VIEW_ATTR             2039
#define IDC_CB_BRUSH                    2040
#define IDC_C_BRUSH_ERASE               2041
#define IDD_INTF                        3001
#define IDC_BROWSE_SPR                  3006
#define IDC_BROWSE_ANI                  3007
#define IDC_PLAY_ANIMATION              3008
#define IDC_C_PLAY_ANIMATION            3008
#define IDC_VIEW_ZOOM                   3009
#define IDC_C_VIEW_ZOOM                 3009
#define IDC_VIEW_LINE                   3010
#define IDC_C_VIEW_LINE                 3010
#define IDC_EDIT_WIDTH                  3011
#define IDC_EDIT_HEIGHT                 3012
#define IDC_B_INTF_BUTTON               3013
#define IDC_B_INTF_SCROLL_LR            3014
#define IDC_B_INTF_SCROLL_TB            3015
#define IDC_B_INTF_DRAG                 3016
#define IDC_B_INTF_TEXT_WINDOW          3017
#define IDC_C_JUMP_LAYER                3018
#define IDC_EDIT_DEST_LAYER             3019
#define IDC_TREE                        3020
#define IDC_EDIT_INTERFACE_X            3022
#define IDC_EDIT_INTF_X                 3022
#define IDC_EDIT_INTERFACE_Y            3023
#define IDC_EDIT_INTF_Y                 3023
#define IDC_EDIT_RGN_LEFT               3024
#define IDC_EDIT_RGN_TOP                3025
#define IDC_EDIT_RGN_RIGHT              3026
#define IDC_EDIT_RGN_BOTTOM             3027
#define IDC_EDIT_SPR_FILE_NAME          3029
#define IDC_EDIT_ANI_FILE_NAME          3030
#define IDC_B_INTF_DIAL_LR              3031
#define IDC_B_INTF_COLOR_FILL           3032
#define IDC_EDIT_COLOR_FILL_R           3033
#define IDC_EDIT_COLOR_FILL_G           3034
#define IDC_EDIT_COLOR_FILL_B           3035
#define IDC_EDIT_VIEW_LEFT              3036
#define IDC_EDIT_VIEW_TOP               3037
#define IDC_EDIT_VIEW_RIGHT             3038
#define IDC_EDIT_VIEW_BOTTOM            3039
#define IDC_EDIT_MOUSE_X                3040
#define IDC_EDIT_MOUSE_Y                3041
#define IDC_CB_RENDER_TYPE              3042
#define IDC_EDIT_TRANS_DELTA            3043
#define IDC_VIEW_SELECT_TRANS           3045
#define IDC_VIEW_TRANS                  3045
#define IDC_C_VIEW_TRANS                3045
#define IDC_BROWSE_BKG                  3046
#define IDC_B_BROWSE_BKG                3046
#define IDC_C_VIEW_OUTLINE              3047
#define IDC_B_INTF_DIAL_TB              3048
#define IDC_EDIT_MIN_MAX_POS            3049
#define IDC_B_INTF_BUTTON_RADIO         3050
#define IDD_TILE_MAP_OBJ                3500
#define IDC_B_NEW_TILE_MAP_OBJ          3501
#define IDC_B_LOAD_TILE_MAP_OBJ         3502
#define IDC_B_SAVE_TILE_MAP_OBJ         3503
#define IDC_B_SAVE_AS_TILE_MAP_OBJ      3504
#define IDC_E_FILE_NAME_TILE_MAP_OBJ    3505
#define IDC_E_MAP_OBJ_WIDTH             3506
#define IDC_E_MAP_OBJ_HEIGHT            3507
#define IDC_B_MAP_OBJ_SET_SIZE          3508
#define IDC_B_SET_SIZE                  3508
#define IDC_LIST_OBJ_SET                3509
#define IDC_LIST_OBJ_SUB_SET            3510
#define IDM_POPUP_INTERFACE             4001
#define IDM_POPUP_INTF                  4001
#define ID_MENU_LAYER_INSERT            4002
#define ID_MENU_LAYER_ADD               4003
#define ID_MENU_LAYER_DELETE            4004
#define ID_MENU_INTF_ADD                4005
#define ID_MENU_INTF_INSERT             4006
#define ID_MENU_INTF_DELETE             4007
#define ID_MENU_INTF_COPY               4008
#define ID_MENU_INTF_PASTE              4009
#define IDD_SCRIPT                      5001
#define IDC_B_SCRIPT_NEW                5002
#define IDD_HOUSE_INFO                  5002
#define IDC_B_SCRIPT_LOAD               5003
#define IDC_B_SCRIPT_SAVE               5004
#define IDC_B_SCRIPT_SAVE_AS            5005
#define IDC_E_SCRIPT_FILE_NAME          5006
#define IDC_E_SCRIPT_USAGE              5007
#define IDC_SPREAD_SCRIPT               5008
#define IDM_POPUP_SCRIPT                6001
#define ID_SCRIPT_REDUCE_WIDTH          6002
#define ID_SCRIPT_EXPAND_WIDTH          6003
#define ID_SCRIPT_REPAIR_WIDTH          6004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1166
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
